name: Test

on:
  push:
    branches:
      - master
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Something
        run: |-
          echo "Hello World!"
