name: Test Manually Workflow

on:
  workflow_dispatch:
jobs:
  print-hello-world-manually:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print Something
        run: |-
          echo "Hello World Manually!"

        #git ls-remote --tags origin
        #echo ${$(git ls-remote --tags origin | tail -1 | awk '{print $2}')#refs/tags/}
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Print Tag
        run: |-
          echo "Current Tag  ${{ steps.previoustag.outputs.tag }}"
