name: Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  print-hello-world-manually:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/debug'
    steps:
      - uses: actions/checkout@v2
      - name: Print Something
        run: |-
          echo "Hello World Manually!"
