name: Test Manually Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  print-hello-world-manually:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: PrintWorkDir
        run: |-
          pwd
          ls -la /home/runner/work/actions_test/actions_test
      - uses: actions/checkout@v2
      - name: Print Something
        run: |-
          echo "Hello World Manually!"
          ls -la /home/runner/work/actions_test/actions_test
          echo "{{$GITHUB_REF}}"
          git describe --tags $(git rev-list --tags --max-count=1)
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          fallback: 1.0.0
      - name: Print Tag
        run: |-
          echo "Current Tag  ${{ steps.currenttag.outputs.tag }}"
